
package com.mrprez.gencross.edit.webservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-03-19T18:39:43.531+01:00
 * Generated source version: 2.5.2
 */

@WebFault(name = "Exception", targetNamespace = "http://service.web.gencross.mrprez.com/")
public class Exception_Exception extends java.lang.Exception {
    
    private com.mrprez.gencross.edit.webservice.Exception exception;

    public Exception_Exception() {
        super();
    }
    
    public Exception_Exception(String message) {
        super(message);
    }
    
    public Exception_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, com.mrprez.gencross.edit.webservice.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, com.mrprez.gencross.edit.webservice.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public com.mrprez.gencross.edit.webservice.Exception getFaultInfo() {
        return this.exception;
    }
}
