package com.mrprez.gencross.edit.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-03-19T18:39:43.593+01:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://service.web.gencross.mrprez.com/", name = "PersonnageService")
@XmlSeeAlso({ObjectFactory.class})
public interface PersonnageService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAvailablePersonnageList", targetNamespace = "http://service.web.gencross.mrprez.com/", className = "com.mrprez.gencross.edit.webservice.GetAvailablePersonnageList")
    @WebMethod
    @ResponseWrapper(localName = "getAvailablePersonnageListResponse", targetNamespace = "http://service.web.gencross.mrprez.com/", className = "com.mrprez.gencross.edit.webservice.GetAvailablePersonnageListResponse")
    public java.util.List<com.mrprez.gencross.edit.webservice.PluginDescription> getAvailablePersonnageList() throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPersonnageList", targetNamespace = "http://service.web.gencross.mrprez.com/", className = "com.mrprez.gencross.edit.webservice.GetPersonnageList")
    @WebMethod
    @ResponseWrapper(localName = "getPersonnageListResponse", targetNamespace = "http://service.web.gencross.mrprez.com/", className = "com.mrprez.gencross.edit.webservice.GetPersonnageListResponse")
    public java.util.List<com.mrprez.gencross.edit.webservice.PersonnageDescription> getPersonnageList(
        @WebParam(name = "type", targetNamespace = "")
        java.lang.String type
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPersonnage", targetNamespace = "http://service.web.gencross.mrprez.com/", className = "com.mrprez.gencross.edit.webservice.GetPersonnage")
    @WebMethod
    @ResponseWrapper(localName = "getPersonnageResponse", targetNamespace = "http://service.web.gencross.mrprez.com/", className = "com.mrprez.gencross.edit.webservice.GetPersonnageResponse")
    public byte[] getPersonnage(
        @WebParam(name = "id", targetNamespace = "")
        java.lang.Integer id,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    ) throws Exception_Exception;
}
