package com.mrprez.gencross.edit.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-03-19T18:39:43.625+01:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "PersonnageServiceService", 
                  wsdlLocation = "M:/workspace/GenCrossWeb/PersonnageServiceService.wsdl",
                  targetNamespace = "http://service.web.gencross.mrprez.com/") 
public class PersonnageServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.web.gencross.mrprez.com/", "PersonnageServiceService");
    public final static QName PersonnageServicePort = new QName("http://service.web.gencross.mrprez.com/", "PersonnageServicePort");
    static {
        URL url = PersonnageServiceService.class.getResource("M:/workspace/GenCrossWeb/PersonnageServiceService.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(PersonnageServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "M:/workspace/GenCrossWeb/PersonnageServiceService.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public PersonnageServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PersonnageServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PersonnageServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns PersonnageService
     */
    @WebEndpoint(name = "PersonnageServicePort")
    public PersonnageService getPersonnageServicePort() {
        return super.getPort(PersonnageServicePort, PersonnageService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PersonnageService
     */
    @WebEndpoint(name = "PersonnageServicePort")
    public PersonnageService getPersonnageServicePort(WebServiceFeature... features) {
        return super.getPort(PersonnageServicePort, PersonnageService.class, features);
    }

}
